# Generated by Django 5.0 on 2023-12-30 03:57

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('years_of_experience', models.IntegerField()),
            ],
            options={
                'db_table': 'coach',
            },
            bases=(models.Model, api.models.Base),
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('utilization_rate', models.IntegerField()),
            ],
            options={
                'db_table': 'resource',
            },
            bases=(models.Model, api.models.Base),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'subject',
            },
            bases=(models.Model, api.models.Base),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'teacher',
            },
            bases=(models.Model, api.models.Base),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_active', models.DateField(auto_now_add=True)),
                ('activity_score', models.IntegerField()),
                ('student_interaction_rating', models.FloatField()),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='api.teacher')),
            ],
            options={
                'db_table': 'activity',
            },
            bases=(models.Model, api.models.Base),
        ),
        migrations.CreateModel(
            name='StudentProgress',
            fields=[
                ('class_id', models.IntegerField(primary_key=True, serialize=False)),
                ('average_score_improvement', models.IntegerField()),
                ('homework_completion_rate', models.IntegerField()),
                ('attendance_rate', models.IntegerField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progresses', to='api.subject')),
            ],
            options={
                'db_table': 'student_progress',
                'unique_together': {('class_id', 'subject_id')},
            },
            bases=(models.Model, api.models.Base),
        ),
        migrations.CreateModel(
            name='ResourceTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='api.resource')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='api.teacher')),
            ],
            options={
                'db_table': 'resource_teacher',
                'unique_together': {('resource_id', 'teacher_id')},
            },
            bases=(models.Model, api.models.Base),
        ),
        migrations.CreateModel(
            name='CoachTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_meeting_date', models.DateField(auto_now_add=True)),
                ('meeting_notes', models.CharField(max_length=512)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='api.coach')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coaches', to='api.teacher')),
            ],
            options={
                'db_table': 'coach_teacher',
                'unique_together': {('coach_id', 'teacher_id')},
            },
            bases=(models.Model, api.models.Base),
        ),
        migrations.CreateModel(
            name='TeacherSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='api.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='api.teacher')),
            ],
            options={
                'db_table': 'teacher_subject',
                'unique_together': {('teacher_id', 'subject_id')},
            },
            bases=(models.Model, api.models.Base),
        ),
    ]
